name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel
        run: |
          python -m pip install pip wheel --upgrade
          python setup.py bdist_wheel

      - name: Install wheel
        run: |
          pip install dist/qdata*

      - name: Install test dependencies
        run: |
          pip install wheel pytest pytest-cov pytest-mock --upgrade

      - name: Run tests
        run: python -m pytest tests --cov=qdata --cov-report=term-missing --tb=native
